import hashlib, io, json, platform, time
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import numpy as np
import torch
from PIL import Image
from transformers import CLIPModel, CLIPProcessor
import transformers

ROOT=Path(r"D:\RESEARCH\DI_MM_V4")
V4=ROOT/"dataset_pipeline"/"v4"
SNAPS=V4/"snapshot_manifest.jsonl"
SHOTS=V4/"screenshots"
OUT=V4/"visuals"
MANIFEST=V4/"visual_manifest.jsonl"
REPORT=ROOT/"gates"/"G1e_visual_generation.json"
PROV=V4/"visual_provenance.json"

MODEL_ID="openai/clip-vit-base-patch32"
COMMIT="3d74acf9a28c67741b2f4f2ea7635f0aaf6f0268"
BATCH=128
LOAD_WORKERS=8

def sha_file(p):
    h=hashlib.sha256()
    with open(p,"rb") as f:
        for c in iter(lambda:f.read(1024*1024),b""):
            h.update(c)
    return h.hexdigest()

def load_rgb(path):
    with Image.open(path) as im:
        return im.convert("RGB").copy()

def main():
    rows=[json.loads(x) for x in SNAPS.read_text(encoding="utf-8").splitlines() if x.strip()]
    rows.sort(key=lambda r:(r["domain"],r["snapshot_id"]))
    missing=[]
    for r in rows:
        p=SHOTS/r["domain"]/f"{r['snapshot_id']}.png"
        if not p.exists():
            missing.append(str(p))
    if missing:
        raise RuntimeError(f"missing {len(missing)} screenshots; first={missing[:5]}")

    OUT.mkdir(parents=True,exist_ok=True)
    device=torch.device("cuda" if torch.cuda.is_available() else "cpu")
    processor=CLIPProcessor.from_pretrained(MODEL_ID,revision=COMMIT,use_fast=False)
    model=CLIPModel.from_pretrained(MODEL_ID,revision=COMMIT)
    model.eval().to(device)
    actual=getattr(model.config,"_commit_hash",None)
    if actual and actual!=COMMIT:
        raise RuntimeError(f"CLIP commit mismatch {actual} != {COMMIT}")

    items=[]
    started=time.time()
    with ThreadPoolExecutor(max_workers=LOAD_WORKERS) as pool:
        for start in range(0,len(rows),BATCH):
            batch=rows[start:start+BATCH]
            shot_paths=[SHOTS/r["domain"]/f"{r['snapshot_id']}.png" for r in batch]
            imgs=list(pool.map(load_rgb,shot_paths))
            inputs=processor(images=imgs,return_tensors="pt")
            pix=inputs["pixel_values"].to(device,non_blocking=True)
            with torch.inference_mode():
                feats=model.get_image_features(pixel_values=pix)
                feats=feats/feats.norm(dim=-1,keepdim=True).clamp(min=1e-12)
                arr=feats.detach().float().cpu().numpy()
            if arr.shape!=(len(batch),512) or not np.isfinite(arr).all():
                raise RuntimeError(f"bad CLIP output {arr.shape}")
            for j,r in enumerate(batch):
                out=OUT/r["domain"]/f"{r['snapshot_id']}.npy"
                out.parent.mkdir(parents=True,exist_ok=True)
                np.save(out,arr[j].astype(np.float32))
                items.append({
                    "domain":r["domain"],
                    "snapshot_id":r["snapshot_id"],
                    "screenshot_path":str(shot_paths[j].relative_to(ROOT)).replace("\\","/"),
                    "screenshot_sha256":sha_file(shot_paths[j]),
                    "visual_path":str(out.relative_to(ROOT)).replace("\\","/"),
                    "visual_sha256":sha_file(out),
                    "dim":512,
                })
            print(f"clip {min(start+BATCH,len(rows))}/{len(rows)}",flush=True)

    items.sort(key=lambda r:(r["domain"],r["snapshot_id"]))
    with MANIFEST.open("w",encoding="utf-8",newline="\n") as f:
        for r in items:
            f.write(json.dumps(r,sort_keys=True,separators=(",",":"))+"\n")
    criteria={
        "all_visuals_generated":len(items)==len(rows),
        "all_vectors_exist":all((ROOT/r["visual_path"]).exists() for r in items),
        "all_screenshots_exist":all((ROOT/r["screenshot_path"]).exists() for r in items),
    }
    verdict="PASS" if all(criteria.values()) else "FAIL_REPAIR"
    prov={
        "gate_id":"G1e_visual_generation",
        "verdict":verdict,
        "model_id":MODEL_ID,
        "model_commit_hash":actual,
        "expected_commit_hash":COMMIT,
        "model_mode":"eval",
        "processor_use_fast":False,
        "normalization":"L2-normalized CLIP image_features",
        "output_dim":512,
        "clip_batch_size":BATCH,
        "image_load_workers":LOAD_WORKERS,
        "render_policy":"Screenshots generated by four deterministic Chromium shards after UnicodeDammit decoding; JavaScript disabled; external network blocked; fixed 1280x720 viewport; device scale 1",
        "snapshots":len(rows),
        "generated":len(items),
        "criteria":criteria,
        "visual_manifest_sha256":hashlib.sha256(MANIFEST.read_bytes()).hexdigest(),
        "torch_version":torch.__version__,
        "transformers_version":transformers.__version__,
        "python_version":platform.python_version(),
        "cuda_device":torch.cuda.get_device_name(0) if torch.cuda.is_available() else None,
        "elapsed_seconds":time.time()-started,
    }
    PROV.write_text(json.dumps(prov,indent=2)+"\n",encoding="utf-8")
    REPORT.write_text(json.dumps(prov,indent=2)+"\n",encoding="utf-8")
    print(json.dumps(prov,indent=2),flush=True)
    return 0 if verdict=="PASS" else 3

if __name__=="__main__":
    raise SystemExit(main())
